title: 'Shakespeare Authorship Question: An Overview'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.7290388280525804
  brandStrength: 0.6272401
  lightness: 0.4942656473722309
  brandColors:
    - '#2F214B'
    - '#6442C6'
    - '#F2FFFF'
    - '#F18991'
    - '#FA0D92'
  rhythmicContrast: 0.626642850227654
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: 'Shakespeare Authorship Question: An Overview'
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.06451613
layout_spectrum: 0.4283154
