name: 'Shakespeare Authorship Question: An Overview'
favicon: null
layout_spectrum: 0.10938474698923528
typography_spectrum: 0.27269717887975276
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#313131'
    - '#fefefe'
    - '#626262'
    - '#d0d0d0'
  brandStrength: 0.6875
  lightness: 0.4942656473722309
  saturation: 0.7290388280525804
  rhythmicContrast: 0.626642850227654
purpose: []
