name: 'Shakespeare Authorship Question: An Overview'
favicon: null
layout_spectrum: 0.10938474698923528
typography_spectrum: 0.27269717887975276
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6275339648127556
  lightness: 0.4942656473722309
  saturation: 0.7290388280525804
  rhythmicContrast: 0.626642850227654
purpose: []
