title: 'Shakespeare Authorship Question: An Overview'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7290388280525804
  brandStrength: 0.6875
  rhythmicContrast: 0.626642850227654
  brandColors:
    - '#000000'
    - '#313131'
    - '#fefefe'
    - '#626262'
    - '#d0d0d0'
  lightness: 0.4942656473722309
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: 'Shakespeare Authorship Question: An Overview'
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0
layout_spectrum: 0.4283154
